// for webpack configuration options

module.exports = {
 // 'context' sets the directory where webpack looks for module files you list in
 // your 'require' statements
 context: __dirname + '/app/assets/javascripts',

 entry: __dirname + '/client/application.jsx',

 // 'output' specifies the filepath for saving the bundled output generated by
 // wepback.
 // It is an object with options, and you can interpolate the name of the entry
 // file using '[name]' in the filename.
 // You will want to add the bundled filename to your '.gitignore'.
 output: {
   path: __dirname + '/app/assets/javascripts',
   filename: 'bundle.js'
 },

 // The 'module' and 'loaders' options tell webpack to use loaders.
 // @see http://webpack.github.io/docs/using-loaders.html
 module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        query: {
          presets: [
            'babel-preset-es2015',
            'babel-preset-react',
            'babel-preset-stage-0'
          ].map(require.resolve)
        }
      }
    ]
  }
};
