default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: calendar_development_database

test:
  <<: *default
  database: calendar_test_database

production:
  <<: *default
  database: calendar_production_database
